site_name: StopSearch
site_url: http://stopsearch.caibucai.top
theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections # nav fold
    - navigation.tabs.sections
    - navigation.top
    - navigation.instant
    - navigation.expand
  palette:
    - scheme: default
    - scheme: slate
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

#contents
nav:
  - 首页: index.md
  - 数据结构: 
    - 简介: datastructure/index.md
  - 计算机网络: 
    - 简介: network/index.md
    - TCP: network/tcp.md
    - IP: network/ip.md
    - HTTP: network/http.md
    - 网络编程: network/programming.md
  - 操作系统: os/index.md
  - CPP: 
    - 简介: cpp/index.md
    - STL:
      - Container容器: cpp/container.md
      - Adapter适配器: cpp/adpater.md
      - Iterator迭代器: cpp/iterator.md
      - Algorithm算法: cpp/algorithm.md
      - Functors仿函数: cpp/functor.md
      - Allocator分配器: cpp/allocator.md
  - CUDA: cuda/index.md
  - Linux: linux/index.md
  - DL:
    - CV: cv/index.md
    - LLM: llm/index.md
  - Weekly: weekly/index.md
  - 关于: about/index.md