site_name: StopSearch
site_url: http://stopsearch.caibucai.top

repo_name: 'caibucai22/stop-search'
repo_url: 'https://github.com/caibucai22/stop-search'

theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections # nav fold
    - navigation.tabs.sections
    - navigation.top
    - navigation.instant
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 # (2)!
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#contents
nav:
  - 首页: index.md
  - 数据结构: 
    - 简介: datastructure/index.md
  - 计算机网络: 
    - 简介: network/index.md
    - TCP: network/tcp.md
    - IP: network/ip.md
    - HTTP: network/http.md
    - 网络编程: network/programming.md
  - 操作系统: os/index.md
  - CPP: 
    - 简介: cpp/index.md
    - STL:
      - Container容器: cpp/container.md
      - Adapter适配器: cpp/adpater.md
      - Iterator迭代器: cpp/iterator.md
      - Algorithm算法: cpp/algorithm.md
      - Functors仿函数: cpp/functor.md
      - Allocator分配器: cpp/allocator.md
  - CUDA: cuda/index.md
  - Linux: linux/index.md
  - DL:
    - CV: cv/index.md
    - LLM: llm/index.md
  - Weekly: weekly/index.md
  - 关于: about/index.md


markdown_extensions:
  - admonition  #警告
  - pymdownx.details  #细节折叠
  - pymdownx.superfences  #超级围栏
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.snippets # 片段
  - pymdownx.arithmatex: # 数学公式
      generic: true
  - tables
  - pymdownx.caret  #插入角标符号(`^`)  
  - pymdownx.mark   #双等号(`==`)
  - pymdownx.tilde  #波浪号(`~`)
  - pymdownx.highlight:
      anchor_linenums: true  #代码块行号锚链接，默认false
      use_pygments: true  #在构建期间使用Pygments或在浏览器中使用 JavaScript 语法高亮器进行高亮显示，默认true
      auto_title: true  #自动为所有代码块添加标题，显示正在使用的语言的名称，默认false
      linenums: true #向所有代码块添加行号，默认false
      linenums_style: pymdownx-inline #三种添加行号的方法，建议table或pymdownx-inline。默认table
  - pymdownx.progressbar
